import Head from "next/head";
import Header from "../components/header";
import Card from "../components/card";
import styles from "../styles/Home.module.scss";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>David Kim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <h3>Hello 👋</h3>
        <h3>I'm David, a Product Designer on InfluxData.</h3>
        <p> So far, I've: </p>
        <div className={styles.list}> 
          <div className={styles.gradientBackground}/>
          <Card theme='dark'>Led the development of an open-source design system &#8594;</Card>
          <Card theme='dark'>Desinged to improve collaboration within engineering teams &#8594;</Card>
          <Card theme='dark'>Improved the developer experience of a highly technical platform &#8594;</Card>
        </div>
       
      </main>
      <Footer></Footer>
    </div>
  );
}
