import Head from "next/head";
import Header from "../components/header";
import Card from "../components/card";
import styles from "../styles/Home.module.scss";
import Footer from "../components/footer";
import { useRouter } from 'next/router'
import Link from "next/link";



export default function Home() {

  const router = useRouter();

  function handleClick( href:string){
    router.push(href)
  }


  return (
    <div>
      <Head>
        <title>David Kim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      <main className={styles.main}>
        <section className= {styles.heroBlock}>
        <div className={styles.gradientBackground}/>
        <h3 className= {styles.hero}>
          Design + Engineering <br/>
          <p className={styles.subHeader}>currently at InfluxData (YC13)</p>
        </h3>
        <Link href='/about'> 
          <a className={styles.anchor}> More about me &#8594;</a> 
        </Link>
        </section>
        
        <section className= {styles.workBlock}>
        <p>I am responsible for : </p>
        <div className={styles.list}> 
          <Card theme='dark' onClick={() => handleClick('/about')}>Design, development, product vision, and evangelization of our open-source design system</Card>
          <Card theme='dark' onClick={() => handleClick('/about')}>Deisgn, experimentation, and product vision for our data visualization experience</Card>
        </div>
        </section>
      </main>
      <Footer></Footer>
    </div>
  );
}
